config/routes.rb
# Project:: IDU0200
# Author::  Janno Põldma (139015 FAY)
# Version:: 1.0 (11.06.2014)

Dokumendid::Application.routes.draw do
  root "documents#index"

  resources :catalogs do
    resources :documents, only: [:index, :new, :create]
  end

  resources :documents, only: [:show, :edit, :update, :destroy]

  get "documents/attributes/:id", to: "documents#attributes"

  get "clipboard/add/:id", to: "clipboard#add"
  get "clipboard/remove/:id", to: "clipboard#remove"
  get "clipboard/index/:catalog", to: "clipboard#index"
  get "clipboard/clear", to: "clipboard#clear"
  get "clipboard/paste/:catalog", to: "clipboard#paste"

  get "sign_in", to: "session#sign_in"
  post "sign_in", to: "session#sign_in"

  get "sign_out", to: "session#sign_out"

  get 'static/log'

  get "search/index", to: "search#index"
  post "search/results", to: "search#results"

  get "forms/:form_name/attributes/:doc_type", to: "forms#attributes"
end

app/controllers/search_controller.rb
# Project:: IDU0200
# Author::  Janno Põldma (139015 FAY)
# Version:: 1.0 (11.06.2014)

class SearchController < ApplicationController
  before_filter :load_context

  def index
    @criteria = SearchCriteria.new({})
  end

  def results
    @criteria = SearchCriteria.new(params[:document])
    result_set = Document.search_documents(@criteria).map { |d| { doc: d, path: edit_document_path(d) } }

    @current_catalog = DocCatalog.find(@criteria.catalog) rescue nil
    @attributes = DocTypeAttribute.where("doc_type_fk = ?", @criteria.type.to_i)

    documents_xml = Nokogiri::XML(result_set.to_xml)
    template = Nokogiri::XSLT(File.read(File.join(Rails.root, "app", "views", "search", "documents.xslt")))

    @content = template.transform(documents_xml).to_s

    render action: :index
  end

  def load_context
    @root = DocCatalog.root
    @doc_status_types = DocStatusType.order(:type_name).all
    @doc_types = DocType.joins(:doc_types).where('"doc_type"."level" = 1').uniq.all
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/_sidebar.html.haml
%ul{:class => ("document-list" if catalog == @root)}
  %li{:class => ("active" if ((@current_catalog.nil? and catalog == @root) or (@current_catalog and @current_catalog == catalog)))}
    = link_to catalog.name, "#", :"data-catalog" => (catalog == @root ? "" : catalog.full_path), :"data-id" => (catalog == @root ? "" : catalog.id)
    = render partial: "sidebar", collection: catalog.doc_catalogs, as: :catalog

app/views/search/index.html.haml
- content_for :head do
  :javascript
    $(document).ready(function () {
      var attr_value = "#{@criteria.attribute_value}";
      var attr_data = {
        #{(@attributes || []).map { |a| "#{a.doc_type_attribute}: \"#{@criteria.attribute[a.doc_type_attribute.to_s]}\"" }.join(",")}
      };
      var $doc_type = $("#document_type");
      function updateItems() {
        var value = $doc_type.find("option:selected").val() || 0;
        $.ajax({ url: "#{@root_path}forms/search/attributes/" + value, dataType: "script", complete: function() {
          if (attr_data) {
            for (var key in attr_data) {
              if (attr_data[key]) {
                $("input#document_attribute_" + key).val(attr_data[key]);
                $("select#document_attribute_" + key + " option[value=" + attr_data[key] + "]").attr("selected", "selected");
              }
            }
            attr_data = null;
          }
          if (attr_value) {
            $("input#document_attribute_value").val(attr_value);
            attr_value = null;
          }
        } });
      }
      if ($("div#attributes").children().length == 0) {
        updateItems();
      }
      $doc_type.change(function () {
        updateItems();
      });
      $(".document-list a").click(function() {
        $(".document-list li").removeClass("active");
        $(this).parent().addClass("active");
        $("#document_catalog").val($(this).attr("data-catalog"));
        $("#document_catalog_value").val($(this).attr("data-id"));
        return false;
      });
      $(".btn-clear-form").click(function() {
        $("form input[type='text']").val("");
        $("#document_catalog_value").val("");
        $("form select option").removeAttr("selected");
        $("form select option:first").attr("selected", "selected");
        $(".document-list li").removeClass("active");
        $(".document-list > li").addClass("active");
        updateItems();
        return false;
      });
    });

.panel-group#accordion
  .panel.panel-default
    .panel-heading
      %h4.panel-title
        -if @content
          %a(data-toggle="collapse" data-parent="#accordion" href="#collapseOne") Otsingu kriteeriumid
        -else
          Otsingu kriteeriumid
    #collapseOne.panel-collapse.collapse{:class => ("in" if @content.nil?)}
      .panel-body
        = form_tag search_results_path, class: "form-horizontal vspace-10" do
          .form-group
            %label.col-sm-3.control-label.input-sm(for="document_id") Id
            .col-sm-1
              %input.form-control.input-sm{id: "document_id", name: "document[id]", type: "text", value: @criteria.id}
          .form-group
            %label.col-sm-3.control-label.input-sm(for="document_name") Nimetus
            .col-sm-5
              %input.form-control.input-sm{id: "document_name", name: "document[name]", type: "text", value: @criteria.name}
          .form-group
            %label.col-sm-3.control-label.input-sm(for="document_description") Kirjeldus
            .col-sm-5
              %input.form-control.input-sm{id: "document_description", name: "document[description]", type: "text", value: @criteria.description}
          .form-group
            %label.col-sm-3.control-label.input-sm(for="document_updated_by") Viimane muutja
            .col-sm-5
              %input.form-control.input-sm{id: "document_updated_by", name: "document[updated_by]", type: "text", value: @criteria.updated_by}
          .form-group
            %label.col-sm-3.control-label.input-sm(for="document_catalog") Kataloogi nimi
            .col-sm-5
              %input.form-control.input-sm{id: "document_catalog", type: "text", readonly: "readonly", value: (@current_catalog ? @current_catalog.full_path : "")}
              %input.form-control.input-sm{id: "document_catalog_value", name: "document[catalog]", type: "hidden", value: (@current_catalog ? @current_catalog.id : "")}
          .form-group
            %label.col-sm-3.control-label.input-sm(for="document_status") Staatus
            .col-sm-5
              %select.form-control.input-sm#doc_type(id="document_status" name="document[status]")
                %option(value="")
                - @doc_status_types.each do |doc_status_type|
                  %option{value: doc_status_type.doc_status_type, selected: (doc_status_type.doc_status_type == @criteria.status.to_i ? "selected" : false)}= doc_status_type.type_name
          %hr
          .form-group
            %label.col-sm-3.control-label.input-sm(for="document_type") Dokumendi tüüp
            .col-sm-5
              %select.form-control.input-sm(id="document_type" name="document[type]")
                %option(value="")
                - @doc_types.each do |doc_type|
                  %optgroup{:label => doc_type.type_name}
                    - doc_type.doc_types.each do |sub_doc_type|
                      %option{value: sub_doc_type.id, selected: (sub_doc_type.id == @criteria.type.to_i ? "selected" : false)}= sub_doc_type.type_name
          %hr
          #attributes
          %hr
          .form-group
            .col-sm-offset-3.col-sm-5
              %button.btn.btn-primary.btn-sm(type="submit") Käivita otsing
              = link_to "Tühjenda vorm", "#", class: "btn btn-default btn-sm btn-clear-form"
  -unless @content.nil?
    = @content.html_safe