config/routes.rb
# Project:: IDU0200
# Author::  Janno Põldma (139015 FAY)
# Version:: 1.0 (11.06.2014)

Dokumendid::Application.routes.draw do
  root "documents#index"

  resources :catalogs do
    resources :documents, only: [:index, :new, :create]
  end

  resources :documents, only: [:show, :edit, :update, :destroy]

  get "documents/attributes/:id", to: "documents#attributes"

  get "clipboard/add/:id", to: "clipboard#add"
  get "clipboard/remove/:id", to: "clipboard#remove"
  get "clipboard/index/:catalog", to: "clipboard#index"
  get "clipboard/clear", to: "clipboard#clear"
  get "clipboard/paste/:catalog", to: "clipboard#paste"

  get "sign_in", to: "session#sign_in"
  post "sign_in", to: "session#sign_in"

  get "sign_out", to: "session#sign_out"

  get 'static/log'

  get "search/index", to: "search#index"
  post "search/results", to: "search#results"

  get "forms/:form_name/attributes/:doc_type", to: "forms#attributes"
end

app/controllers/documents_controller.rb
# Project:: IDU0200
# Author::  Janno Põldma (139015 FAY)
# Version:: 1.0 (11.06.2014)

class DocumentsController < ApplicationController
  before_filter :load_catalog_context, except: [:attributes, :add_to_buffer, :remove_from_buffer]
  before_filter :load_document_context, only: [:new, :edit, :create, :update]

  def index
    session[:buffer] ||= []
    @buffer = session[:buffer]
    folder_count = @current_catalog.documents.to_a.count { |d| @buffer.include? d.document }
    @buffer_size = @buffer.size - folder_count
  end

  def new
    if @current_catalog == @root then
      redirect_to catalog_documents_path(0)
    else
      @document = Document.new
    end
  end

  def create
    if @current_catalog.nil? or @current_catalog == @root then
      redirect_to catalog_documents_path(0)
    else
      doc_type = DocType.find(params[:document][:doc_type].to_i) rescue nil
      @document = Document.new({ name: params[:document][:name],
                                 description: params[:document][:description],
                                 doc_type: doc_type,
                                 doc_status_type_fk: params[:document][:doc_status_type],
                                 created: DateTime.now,
                                 created_by: @current_user.employee.employee,
                                 updated: DateTime.now,
                                 updated_by: @current_user.employee.employee,
                                 current_user: @current_user })
      @document.build_document_doc_catalog(doc_catalog: @current_catalog,
                                           catalog_time: DateTime.now,
                                           current_user: @current_user)
      unless doc_type.nil? then
        @document.build_document_doc_type(doc_type: doc_type)
        doc_type.doc_type_attributes.each do |doc_type_attribute|
          value = params[:document][:attributes][doc_type_attribute.doc_type_attribute.to_s]
          attribute = @document.doc_attributes.build(doc_type_attribute.to_doc_attribute(value))
          attribute.doc_type_attribute = doc_type_attribute
          attribute.value = value unless value.nil?
        end
      end
      if @document.save then
        redirect_to catalog_documents_path(@current_catalog), notice: "Dokumendi lisamine õnnestus."
      else
        render action: :new
      end
    end
  end

  def edit
    @document = Document.find(params[:id]) rescue not_found
    @current_catalog = @document.doc_catalog
  end

  def update
    now = DateTime.now
    @document = Document.find(params[:id]) rescue not_found
    @current_catalog = @document.doc_catalog
    @document.update_attributes({ name: params[:document][:name],
                                  description: params[:document][:description],
                                  doc_status_type_fk: params[:document][:doc_status_type],
                                  updated: now,
                                  updated_by: @current_user.employee.employee,
                                  current_user: @current_user })
    @document.doc_catalog.update_attributes({ content_updated: now,
                                              content_updated_by: @current_user.employee.employee })
    @document.doc_attributes.each do |doc_attribute|
      doc_attribute.update_attributes({ value: params[:document][:attributes][doc_attribute.doc_attribute.to_s] })
    end
    if @document.save then
      redirect_to catalog_documents_path(@current_catalog), notice: "Dokumendi andmed muudetud."
    else
      render action: :edit
    end
  end

  def attributes
    if request.xhr?
      @doc_type = DocType.find(params[:id]) rescue not_found
    else
      not_found
    end
  end

  def destroy
    @document = Document.find(params[:id]) rescue not_found
    @current_catalog = @document.doc_catalog
    #@document.document_doc_catalog.current_user = @current_user
    #@document.destroy
    Document.delete_sp(@document, @current_user)
    redirect_to catalog_documents_path(@current_catalog), notice: "Dokument on kustutatud."
  end

  private

  def load_catalog_context
    @root = DocCatalog.root
    if params[:catalog_id].to_i == 0 then
      @current_catalog = @root
    else
      @current_catalog = DocCatalog.find(params[:catalog_id]) rescue not_found
    end
  end

  def load_document_context
    @document_types = DocType.joins(:doc_types).where('"doc_type"."level" = 1').uniq.all
    @doc_status_types = DocStatusType.order(:type_name).all
  end
end

app/helpers/documents_helper.rb
# Project:: IDU0200
# Author::  Janno Põldma (139015 FAY)
# Version:: 1.0 (11.06.2014)

module DocumentsHelper
  def document_attribute(attribute, id)
    case attribute.data_type_id
    when 1 then doc_attribute_text(attribute, id, :value_text)
    when 2 then doc_attribute_text(attribute, id, :value_number)
    when 3 then doc_attribute_text(attribute, id, :value_date)
    when 4 then doc_attribute_select(attribute, id, :atr_type_selection_value_fk)
    else raise "Unknown attribute type: #{attribute.data_type_id}"
    end
  end

  def bs_doc_attribute(doc_attribute, id_value)
    id = "document_attributes_#{id_value}"
    name = "document[attributes][#{id_value}]"

    options = { errors: doc_attribute.errors[:base] }
    options[:required] = true if doc_attribute.required.upcase == "Y"

    bs_control(id, doc_attribute.type_name.capitalize, options) do
      case doc_attribute.data_type
      when DocAttribute::DATA_TYPE_TEXT, DocAttribute::DATA_TYPE_NUMBER, DocAttribute::DATA_TYPE_DATE then
        tag "input", class: "form-control input-sm", id: id, name: name, type: "text", value: doc_attribute.value
      when DocAttribute::DATA_TYPE_CHOICE then
        collection_key = options[:key] || :id
        collection_value = options[:value] || :value_text
        content_tag(:select, class: "form-control input-sm", id: id, name: name) do
          concat_content_tag :option, value: "" do
          end
          doc_attribute.doc_attribute_type.atr_type_selection_values.each do |value|
            tag_options = { value: value.atr_type_selection_value }
            if value.atr_type_selection_value == doc_attribute.atr_type_selection_value_fk then
              tag_options[:selected] = "selected"
            end
            concat_content_tag :option, tag_options do
              value.value_text
            end
          end
        end
      else
        raise "Unknown attribute type: #{doc_attribute.data_type}"
      end
    end
  end

  def bs_text_field(object, property, text, value, options = {})
    id = object.to_s + "_" + property.to_s
    name = object.to_s + "[" + property.to_s + "]"
    options[:errors] = self.instance_variable_get("@#{object}").errors[property]
    bs_control id, text, options do
      tag_options = { class: "form-control input-sm", id: id, name: name, type: "text", value: value }
      tag_options[:readonly] = "readonly" if options[:readonly]
      tag "input", tag_options
    end
  end

  def bs_text_area(object, property, text, value, options = {})
    id = object.to_s + "_" + property.to_s
    name = object.to_s + "[" + property.to_s + "]"
    options[:errors] = self.instance_variable_get("@#{object}").errors[property]
    bs_control id, text, options do
      content_tag :textarea, class: "form-control input-sm", id: id, name: name, rows: 3 do
        value
      end
    end
  end

  def bs_select(object, property, text, collection, value, options = {})
    id = object.to_s + "_" + property.to_s
    name = object.to_s + "[" + property.to_s + "]"
    collection_key = options[:key] || :id
    collection_value = options[:value] || :value_text
    options[:errors] = self.instance_variable_get("@#{object}").errors[property]
    bs_control id, text, options do
      content_tag :select, class: "form-control input-sm", id: id, name: name do
        concat_content_tag :option, value: "" do
        end
        collection.each do |item|
          tag_options = { value: item.send(collection_key) }
          tag_options[:selected] = "selected" if item == value
          concat_content_tag :option, tag_options do
            item.send(collection_value) 
          end
        end
      end
    end
  end

  def bs_grouped_select(object, property, text, collection, value, options = {})
    id = object.to_s + "_" + property.to_s
    name = object.to_s + "[" + property.to_s + "]"
    collection_key = options[:key] || :id
    collection_value = options[:value] || :value_text
    collection_group_method = options[:group] || :group
    collection_group_label = options[:label] || :label
    options[:errors] = self.instance_variable_get("@#{object}").errors[property]
    bs_control id, text, options do
      content_tag :select, class: "form-control input-sm", id: id, name: name do
        concat (content_tag :option, value: "" do
        end)
        collection.each do |item|
          label = item.send(collection_group_label)
          group = item.send(collection_group_method)
          html = content_tag :optgroup, label: label do
            group.each do |elem|
              tag_options = { value: elem.send(collection_key) }
              tag_options[:selected] = "selected" if elem == value
              concat (content_tag :option, tag_options do
                elem.send(collection_value) 
              end)
            end
          end
          concat html
        end
      end
    end
  end

  private

  def concat_content_tag(name, content_or_options_with_block = nil, options = nil, escape = true, &block)
    concat content_tag(name, content_or_options_with_block, options, escape, &block)
  end

  def bs_control(id, text, options)
    errors = options[:errors] || []

    classes = ["form-group"]
    classes << "required" if options[:required] || false
    classes << "has-error" if errors.any?

    content_tag :div, class: classes.join(" ") do
      concat_content_tag :label, class: "col-sm-2 control-label input-sm", for: id do
        text
      end
      concat_content_tag :div, class: "col-sm-5" do
        yield
      end
      if errors.any? then
        concat_content_tag :div, class: "col-sm-5" do
          errors.each do |message|
            concat_content_tag :p, class: "help-block" do
              content_tag :small do
                message
              end
            end
          end
        end
      end
    end
  end

  def doc_attribute_name(attribute, id)
    "document[attributes][#{id}]"
  end

  def doc_attribute_placeholder_for(property)
    case property
    when :value_text then 'Mingi tekst'
    when :value_number then 12345
    when :value_date then 'PP.KK.AAAA'
    end
  end

  def doc_attribute_label(attribute, name)
    label_tag name, class: "col-sm-2 control-label input-sm" do
      "#{attribute.doc_attribute_type.type_name.capitalize}"
    end
  end

  def doc_attribute_text(attribute, id, property)
    doc_attribute_control attribute, id do |name|
      value = attribute[property]
      placeholder = doc_attribute_placeholder_for property
      concat text_field_tag(name, value, class: "form-control input-sm", placeholder: placeholder)
    end
  end

  def doc_attribute_select(attribute, id, property)
    html_options = {include_blank: true, class: "form-control input-sm"}
    doc_attribute_control attribute, id do |name|
      collection = attribute.doc_attribute_type.atr_type_selection_values
      options = options_from_collection_for_select(collection, :atr_type_selection_value, :value_text, attribute[property])
      select_tag name, options, html_options
    end
  end

  def doc_attribute_control(attribute, id)
    content_tag :div, class: (attribute.required == 'Y' ? "form-group required" : "form-group") do
      name = doc_attribute_name attribute, id
      label_html = doc_attribute_label attribute, name
      control_html = content_tag :div, class: "col-sm-5" do
        yield name
      end
      concat label_html
      concat control_html
    end
  end
end

app/views/documents/_current_catalog.html.haml
- if item != @root
  = render partial: "current_catalog", locals: { is_first: false, item: (item.doc_catalog || @root) }
- if is_first and not @document
  %li.active= item.name
- else
  %li= link_to item.name, catalog_documents_path(item)

app/views/documents/_sidebar.html.haml
%ul{:class => ("document-list" if catalog == @root)}
  %li{:class => ("active" if catalog == @current_catalog)}
    = link_to catalog.name, catalog_documents_path(catalog)
    = render partial: "sidebar", collection: catalog.doc_catalogs, as: :catalog

app/views/documents/edit.html.haml
%h4 Dokumendi muutmine

= form_tag document_path(@document), method: :put, class: "form-horizontal" do
  = bs_text_field :document, :doc_type, "Tüüp", @document.doc_type.type_name, required: true, readonly: true
  = bs_text_field :document, :name, "Nimetus", @document.name, required: true
  = bs_text_area :document, :description, "Kirjeldus", @document.description
  = bs_select :document, :doc_status_type, "Staatus", @doc_status_types, @document.doc_status_type, required: true, key: :doc_status_type, value: :type_name
  - if @document.doc_attributes.any?
    %h3
      %small Dokumendi atribuudid
    - @document.doc_attributes.each do |attribute|
      = bs_doc_attribute attribute, attribute.doc_attribute
  %hr
  .form-group
    .col-sm-offset-2.col-sm-5
      %button.btn.btn-primary.btn-sm(type="submit") Salvesta
      = link_to "Tühista", catalog_documents_path(@current_catalog), class: "btn btn-default btn-sm"

- unless @document.updated.nil?
  .well.well-sm
    %small
      = "Dokumendi andmeid on viimati muudetud #{@document.updated.strftime("%d.%m.%Y kell %H:%M:%S")}" + (@document.employee.nil? ? "." : " töötaja #{@document.employee.person.full_name} poolt.")

app/views/documents/index.html.haml
- content_for :head do
  :javascript
    $(document).ready(function () {
      var bufferSize = #{@buffer_size};
      function updateBuffer() {
        var count = bufferSize + $(".add-to-buffer:checked").length;
        if (count == 0) {
          $(".btn-buffer").addClass("disabled");
        } else {
          $(".btn-buffer").removeClass("disabled");
        }
      }
      $(".add-to-buffer").change(function () {
        var $tr = $(this).parent().parent();
        if (this.checked) {
          $tr.animate_from_to(".fa-clipboard");
          $tr.addClass("success");
          $.ajax({ url: "#{@root_path}clipboard/add/" + $(this).attr("data-id"), dataType: "script" });
        } else {
          $(".fa-clipboard").animate_from_to($tr, {
            callback: function() { $tr.removeClass("success"); }
          });
          $.ajax({ url: "#{@root_path}clipboard/remove/" + $(this).attr("data-id"), dataType: "script" });
        }
        updateBuffer();
      });
      updateBuffer();
      $("#btn-open-buffer").click(function() {
        $.ajax({ url: "#{@root_path}clipboard/index/#{@current_catalog.id}", dataType: "script" });
      });
      $("#btn-paste-buffer").click(function() {
        $.getJSON("#{@root_path}clipboard/paste/#{@current_catalog.id}?" + (new Date().getTime()),
                  function(data) {
                    window.location.href = data.url;
                  } 
        );
      });
    });

-if flash[:notice]
  .alert.alert-success.alert-dismissable
    %button.close{:type => "button", :"data-dismiss" => "alert", :"aria-hidden" => "true"} &times;
    = flash[:notice]

- if @current_catalog.documents.any?
  %table.table.table-hover.table-condensed.files
    %thead
      %tr
        %th
          %i.fa.fa-cut{:title => "Vali liigutamiseks"}
        %th Id
        %th Dokumendi nimi
        %th &nbsp;
    %tbody
      - @current_catalog.documents.each do |document|
        %tr{ class: ("success" if @buffer.include? document.document) }
          %td
            = check_box_tag nil, nil, (@buffer.include? document.document), class: "add-to-buffer", :"data-id" => document.document
          %td= document.document
          %td
            = link_to document.name, edit_document_path(document)
          %td.text-right
            = link_to document_path(document), method: :delete, data: { confirm: "Kas oled kindel, et soovid dokumendi kustutada?" }, class: "btn btn-danger btn-xs" do
              %i.fa.fa-trash-o
              Kustuta
- elsif @current_catalog == @root
  .alert.alert-warning Juurkataloogi ei ole lubatud dokumente lisada.
- else
  .alert.alert-info Valitud kataloogis ei ole dokumente.

- unless @current_catalog == @root or @current_catalog.content_updated.nil?
  .well.well-sm
    %small
      = "Kataloogi andmeid on viimati muudetud #{@current_catalog.content_updated.strftime("%d.%m.%Y kell %H:%M:%S")} töötaja #{@current_catalog.employee.person.full_name} poolt."

app/views/documents/new.html.haml
- content_for :head do
  :javascript
    $(document).ready(function () {
      var $doc_type = $("#document_doc_type");
      function updateItems() {
        var value = $doc_type.find("option:selected").val();
        if (value) {
          $doc_type.find("option[value='']").remove();
          $.ajax({ url: "#{@root_path}documents/attributes/" + value, dataType: "script" });
        }
      }
      if ($("div#attributes").length == 0) {
        updateItems();
      } else {
        var value = $doc_type.find("option:selected").val();
        if (value) {
          $doc_type.find("option[value='']").remove();
        }
      }
      $doc_type.change(function () {
        updateItems();
      });
    });

%h4 Uue dokumendi lisamine

- if @document.errors.any?
  .alert.alert-danger
    %p
      %small
        %strong Lisatava dokumendi andmed on puudulikud!
        Palun paranda allpool välja toodud vead.

= form_tag catalog_documents_url(@current_catalog, @document), class: "form-horizontal" do
  = bs_grouped_select :document, :doc_type, "Tüüp", @document_types, @document.doc_type, required: true, key: :id, value: :type_name, group: :doc_types, label: :type_name
  = bs_text_field :document, :name, "Nimetus", @document.name, required: true
  = bs_text_area :document, :description, "Kirjeldus", @document.description
  = bs_select :document, :doc_status_type, "Staatus", @doc_status_types, @document.doc_status_type, required: true, key: :doc_status_type, value: :type_name
  - if @document.doc_attributes.any?
    #attributes
      %h3
        %small Dokumendi atribuudid
      - @document.doc_attributes.each do |attribute|
        = bs_doc_attribute(attribute, attribute.doc_type_attribute.doc_type_attribute)
  %hr
  .form-group
    .col-sm-offset-2.col-sm-5
      %button.btn.btn-primary.btn-sm(type="submit") Salvesta
      = link_to "Tühista", catalog_documents_path(@current_catalog), class: "btn btn-default btn-sm"