config/routes.rb
# Project:: IDU0200
# Author::  Janno Põldma (139015 FAY)
# Version:: 1.0 (11.06.2014)

Dokumendid::Application.routes.draw do
  root "documents#index"

  resources :catalogs do
    resources :documents, only: [:index, :new, :create]
  end

  resources :documents, only: [:show, :edit, :update, :destroy]

  get "documents/attributes/:id", to: "documents#attributes"

  get "clipboard/add/:id", to: "clipboard#add"
  get "clipboard/remove/:id", to: "clipboard#remove"
  get "clipboard/index/:catalog", to: "clipboard#index"
  get "clipboard/clear", to: "clipboard#clear"
  get "clipboard/paste/:catalog", to: "clipboard#paste"

  get "sign_in", to: "session#sign_in"
  post "sign_in", to: "session#sign_in"

  get "sign_out", to: "session#sign_out"

  get 'static/log'

  get "search/index", to: "search#index"
  post "search/results", to: "search#results"

  get "forms/:form_name/attributes/:doc_type", to: "forms#attributes"
end

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width,initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "Dokumendid"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"

    = yield :head


  %body
    .navbar.navbar-default.navbar-static-top(role="navigation")
      .container
        .navbar-header
          %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-collapse")
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to root_path, {class: "navbar-brand"} do
            %i.fa.fa-files-o
            Dokumendid
        .collapse.navbar-collapse
          -if @current_user
            %ul.nav.navbar-nav.navbar-right
              %li{class: ("active" if controller_name == "search")}
                = link_to search_index_path do
                  %i.fa.fa-search
                  Otsing
              %li.dropdown
                %a.dropdown-toggle(href="#" data-toggle="dropdown")
                  %i.fa.fa-user
                  = @current_user.employee.person.full_name
                  %b.caret
                %ul.dropdown-menu
                  %li= link_to "Rakenduse logi", static_log_path
                  %li.divider
                  %li= link_to "Logi välja", sign_out_path

    .container
      .row
        .col-lg-3
          = yield(:sidebar)
        .col-lg-9
          = yield(:breadcrumbs)
          = yield
      %footer
        %p &copy; Something 2014

app/views/layouts/documents.html.haml
- content_for :sidebar do
  .well.sidebar-nav
    = render "sidebar", catalog: @root

- content_for :breadcrumbs do
  %ol.breadcrumb
    = render partial: "current_catalog", locals: { is_first: true, item: @current_catalog }
    - if @document.nil? and @current_catalog != @root
      %span.pull-right
        .btn-group
          %a.btn.btn-primary.btn-buffer.btn-xs.dropdown-toggle.disabled(data-toggle="dropdown")
            %i.fa.fa-clipboard
            Puhver
            %span.caret
          %ul.dropdown-menu.pull-right
            %li
              %a(href="#" id="btn-paste-buffer")
                %i.fa.fa-fw.fa-download
                Aseta kausta
              %a(href="#" id="btn-open-buffer")
                %i.fa.fa-fw.fa-list
                Vaata valitud faile&hellip;
        = link_to new_catalog_document_path(@current_catalog), {class: "btn btn-success btn-xs"} do
          %i.fa.fa-file-text-o
          Lisa uus dokument

= render template: "layouts/application"

app/views/layouts/search.html.haml
- content_for :sidebar do
  .well.sidebar-nav
    = render "sidebar", catalog: @root

= render template: "layouts/application"